#!/usr/bin/env bash

export CONTECO_LABEL="kafka_connect.base - ContEco"
export CONTECO_DESCRIPTION="Confluent Kafka Connect base image, with configuration changes."

export CONTECO_TYPE="kafka_connect"
export CONTECO_NAME="base"
export CONTECO_TAG="6.0.0"

export CONTECO_BUILD="image-base"

export CONTECO_EXTERNAL_IMAGE_NAME="vcwebio/conteco.external.kafka_connect:6.0.0"
